SEARCH_DIR("/usr/lib/i386-linux-gnu/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/local/codetyphon/binLibraries/i386-linux/")
SEARCH_DIR("/libx32/")
SEARCH_DIR("/lib32/")
SEARCH_DIR("/usr/lib32/")
SEARCH_DIR("/usr/libx32/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/6/")
SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/lcl/units/i386-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/packager/units/i386-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-js/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/dts/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/xforms/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libcurl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/chm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/hermes/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/lua/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gmp/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-db/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/imlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/sqlite/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/mad/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-sdo/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/svgalib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-sound/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/mariadb/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libenet/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fpindexer/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-json/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libfontconfig/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gnutls/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fpmkunit/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/newt/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libgd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/opengles/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-xml/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-extra/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/ibase/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/syslog/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/hash/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/cdrom/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pcap/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fv/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libpng/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/ptc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-objpas/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/bzip2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/openal/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/aspell/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/numlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libvlc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk1/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-net/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/tcl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/symbolic/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-fpcunit/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/a52/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libxml2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/ldap/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/graph/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/firebird/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gnome1/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/x11/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-web/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-generics/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libusb/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/uuid/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/imagemagick/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libtar/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fpgtk/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libgc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/bfd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/odbc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libmagic/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/opengl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-unicode/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-console/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/users/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-passrc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/dbus/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/openssl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pastojs/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/odata/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-process/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fppkg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/postgres/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rsvg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/httpd22/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/modplug/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/oggvorbis/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/zorba/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gdbint/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/utmp/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/proj4/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/ggi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/webidl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/sdl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/mysql/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fftw/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-async/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libsee/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libcups/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-stl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/cairo/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/opencl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/unzip/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-extra/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/zlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/unixutil/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pxlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/ncurses/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/httpd24/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-pdf/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/jni/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/iconvenc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/libmicrohttpd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pthreads/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/regexpr/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fastcgi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gdbm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/oracle/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/dblib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-res/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-registry/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/i386-linux/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/bin/x86_64-linux/")
INPUT(
/usr/lib/i386-linux-gnu/crti.o
/usr/local/codetyphon/binLibraries/i386-linux/crtbegin.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/si_c21.o
/home/daniel/Dokumente/060_Lazarus-Projekte/000_Neustart-2017-08/Tools/AudioManager/lib/i386-linux/audio_mngr.o
/home/daniel/Dokumente/060_Lazarus-Projekte/000_Neustart-2017-08/Tools/AudioManager/lib/i386-linux/audio_mngr.or
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/system.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/fpintres.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/objpas.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/interfaces.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/forms.o
/home/daniel/Dokumente/060_Lazarus-Projekte/000_Neustart-2017-08/Tools/AudioManager/lib/i386-linux/main.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/cwstring.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/baseunix.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/ctypes.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/unix.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/unixtype.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/initc.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/dynlibs.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/unixcp.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/unixutil.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/dl.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2disableliboverlay.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2int.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/classes.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/sysutils.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/types.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/typinfo.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/rtlconsts.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/sortbase.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/linux.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/errors.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/sysconst.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/math.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/x11/xlib.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/x11/x.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/gdk2x.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/gdk2pixbuf.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/gtk2.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/gdk2.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/glib2.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/pango.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazfileutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazutf8.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/dynhasharray.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/maps.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/integerlist.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazloggerbase.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazstringutils.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/dialogs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/controls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclstrconsts.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lmessages.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclproc.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclintf.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lcltype.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/graphtype.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/graphmath.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/graphics.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/menus.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/themes.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/buttons.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/stdctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/checklst.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/comctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/extctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclplatformdef.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/interfacebase.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wslclclasses.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wscontrols.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2winapiwindow.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2globals.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2proc.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2def.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2fontcache.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2extra.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2msgqueue.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/x11/xrender.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/cairo/cairo.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/atk.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazutilsstrconsts.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/fpcadds.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-objpas/strutils.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/gettext.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazclasses.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazmethodlist.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/laz_avl_tree.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/fgl.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/laztracer.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazutilities.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lresources.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/buttonpanel.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclclasses.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/clipbrd.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lcltaskdialog.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/uitypes.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/fileutil.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-objpas/variants.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazconfigstorage.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/dynqueue.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazutf8classes.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl-objpas/varutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/avglvltree.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazdbglog.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/utf8process.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazsysutils.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpimage.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/intfgraphics.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpreadbmp.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpwritebmp.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/bmpcomn.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpreadpng.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpwritepng.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpreadtiff.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpwritetiff.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fptiffcmn.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclversion.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/icnstypes.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpimgcmn.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/pngcomn.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/zstream.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/zbase.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/gzio.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/hash/crc.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/zdeflate.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/zinflate.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/trees.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/adler.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/infblock.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/infutil.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/infcodes.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/inftrees.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/paszlib/inffast.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazversion.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/contnrs.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpcanvas.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpreadpnm.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpwritepnm.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpreadjpeg.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpwritejpeg.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpreadtga.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpwritetga.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpreadgif.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclrescache.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsreferences.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/clipping.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jpeglib.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdapimin.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdatasrc.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdapistd.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jmorecfg.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdeferr.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jinclude.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jerror.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jmemmgr.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdmarker.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdinput.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcomapi.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jutils.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jmemnobs.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdmaster.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdcolor.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdsample.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdpostct.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jddctmgr.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdphuff.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdhuff.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdcoefct.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdmainct.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jquant1.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jquant2.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdmerge.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdct.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jidctfst.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jidctint.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jidctflt.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jidctred.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcapistd.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcapimin.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jdatadst.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcparam.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcinit.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcmarker.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcphuff.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jchuff.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcmaster.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jccolor.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcsample.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcprepct.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcdctmgr.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jccoefct.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jcmainct.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jfdctint.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jfdctfst.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/pasjpeg/jfdctflt.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/targacmn.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/syncobjs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/tmschema.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/masks.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-process/process.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-process/pipes.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/rtl/termio.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/custapp.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/customtimer.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/actnlist.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/helpintfs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/imglist.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/singleinstance.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fpimgcanv.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/fppixlcanv.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/pixtools.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-image/ellipses.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsimglist.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsproc.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsfactory.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/propertystorage.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/rttiutils.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsmenus.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazlogger.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/chm/fasthtmlparser.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsforms.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/imagelistcache.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/textstrings.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/extendedstrings.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsstdctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsbuttons.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/popupnotifier.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsextctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsdialogs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wschecklst.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/toolwin.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wscomctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wstoolwin.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/gtk2/gtk2ext.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/extdlgs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclmessageglue.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2debug.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/calendar.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/calcform.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wscalendar.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsextdlgs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/messages.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/lclmemmanager.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsprivate.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/uriparser.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wscontrols.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazlinkedlist.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsfactory.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsstdctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wschecklst.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2themes.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/spin.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/grids.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/pairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsspin.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-xml/htmldefs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/maskedit.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/dynamicarray.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/laz2_xmlcfg.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lcsvutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/lazfilecache.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/laz2_dom.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/laz2_xmlread.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/laz2_xmlwrite.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/i386-linux/laz2_xmlutils.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wsgrids.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/wspairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsbuttons.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wscalendar.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wscomctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsdialogs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsextctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsextdlgs.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsforms.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsgrids.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsimglist.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsmenus.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wsspin.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2wspairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/unitywsctrls.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2cellrenderer.o
/usr/local/codetyphon/typhon/lcl/units/i386-linux/gtk2/gtk2listviewtreemodel.o
/usr/local/codetyphon/fpc/fpc64/units/i386-linux/fcl-base/inifiles.o
)
INPUT(
-ldl
-lpthread
-lgdk-x11-2.0
-lX11
-lgdk_pixbuf-2.0
-lgtk-x11-2.0
-lgobject-2.0
-lglib-2.0
-lgthread-2.0
-lgmodule-2.0
-lpango-1.0
-lcairo
-latk-1.0
)
GROUP(
-lc
)
INPUT(
/usr/local/codetyphon/binLibraries/i386-linux/crtend.o
/usr/lib/i386-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
